
# üß™ Data Manipulation Tutorial with Pandas

This tutorial covers essential data manipulation techniques using **pandas** library, including reading/writing files, inspecting data, modifying columns, filtering, grouping, and more.

When working with tabular data, such as spreadsheet, [pandas](https://pandas.pydata.org/pandas-docs/stable/index.html) is a well-known tool used in Python. In pandas, a data table is called as a `DataFrame`. Basically, it is just like your spreadsheet where you have columns, rows, and data in each cell.

In [1]:
# üì¶ Import necessary libraries
import pandas as pd

## üìÑ Creating Dataframe
![DataFrame illustration](https://pandas.pydata.org/pandas-docs/stable/_images/01_table_dataframe.svg "DataFrame illustration taken from pandas.pydata.org")

> Illustration is taken from [pandas.pydata.org](https://pandas.pydata.org)

DataFrame is two-dimensional data structure that can store various type of data, including character, numeric (i.e., integer, floating point), and many more. The following code creates a DataFrame of three columns with label `Name`, `Age`, and `Score` from a dictionary called `data`.

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 20, 28],
    'Score': [85, 90, 88, 76, 95]
}

df = pd.DataFrame(data)
df.head()

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     88
3    David   20     76
4      Eva   28     95


## üìÅ Reading and Writing CSV Files

In [ ]:
# Write to CSV
df.to_csv('../dataset/sample_data.csv', index=False)

In [3]:
# Read the existing CSV file
transactionDf = pd.read_csv('../dataset/sample_customer_transactions.csv')
transactionDf.head()

,transaction_id,transaction_date,customer_id,product_id,product_name,category,quantity,unit_price,store_location,payment_method,delivery_method,discount_applied,demand_type,order_status,customer_rating
0,T0001,2024-08-13,C4310,P117,Beverage Product 6,beverage,5,17.94,New York,cash,home delivery,3.64,seasonal,cancelled,4
1,T0002,2024-11-22,C6417,P749,Canned Product 11,canned,10,7.04,Houston,credit card,pickup,1.67,promotional,completed,5
2,T0003,2024-10-28,C3303,P640,Beverage Product 3,beverage,1,14.19,Chicago,cash,digital download,2.32,seasonal,completed,2
3,T0004,2024-10-16,C7175,P126,Canned Product 3,canned,6,1.51,Chicago,online,home delivery,0.28,promotional,pending,4
4,T0005,2024-03-30,C4760,P730,Canned Product 14,canned,2,13.97,Phoenix,cash,home delivery,4.17,regular,completed,4


## üîç Basic Information and Statistical Summary

In [4]:
# Display basic info
transactionDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    50 non-null     object
 1   transaction_date  50 non-null     object
 2   customer_id       50 non-null     object
 3   product_id        50 non-null     object
 4   product_name      50 non-null     object
 5   category          50 non-null     object
 6   quantity          50 non-null     int64
 7   unit_price        50 non-null     float64
 8   store_location    50 non-null     object
 9   payment_method    50 non-null     object
 10  delivery_method   50 non-null     object
 11  discount_applied  50 non-null     float64
 12  demand_type       50 non-null     object
 13  order_status      50 non-null     object
 14  customer_rating   50 non-null     int64
dtypes: float64(2), int64(2), object(11)
memory usage: 6.0+ KB

In [5]:
# shows statistical summary of numeric columns
transactionDf.describe()

        quantity  unit_price  discount_applied  customer_rating
count  50.000000   50.000000         50.000000         50.00000
mean    5.440000   10.824600          2.655000          3.24000
std     2.785971    5.255466          1.337725          1.34862
min     1.000000    1.510000          0.280000          1.00000
25%     3.000000    6.405000          1.542500          2.00000
50%     5.500000   11.635000          2.940000          3.00000
75%     8.000000   15.090000          3.897500          4.00000
max    10.000000   19.620000          4.780000          5.00000

In [6]:
# shows skewness of numeric columns
transactionDf.select_dtypes(include=['number']).skew()

quantity           -0.057297
unit_price         -0.046861
discount_applied   -0.309945
customer_rating    -0.250106
dtype: float64

## üõ†Ô∏è Modify Columns: Rename, Drop, Add
Any modifications made in a DataFrame object will not change the original `csv` file. Change will be applied once the DataFrame is overwritten the `csv` file through executing `to_csv` function.

In [7]:
# Rename column 'discount_applied' to 'discount_used'
transactionDf.rename(columns={'discount_applied': 'discount_used'}, inplace=True)

transactionDf.head()

,transaction_id,transaction_date,customer_id,product_id,product_name,category,quantity,unit_price,store_location,payment_method,delivery_method,discount_used,demand_type,order_status,customer_rating
0,T0001,2024-08-13,C4310,P117,Beverage Product 6,beverage,5,17.94,New York,cash,home delivery,3.64,seasonal,cancelled,4
1,T0002,2024-11-22,C6417,P749,Canned Product 11,canned,10,7.04,Houston,credit card,pickup,1.67,promotional,completed,5
2,T0003,2024-10-28,C3303,P640,Beverage Product 3,beverage,1,14.19,Chicago,cash,digital download,2.32,seasonal,completed,2
3,T0004,2024-10-16,C7175,P126,Canned Product 3,canned,6,1.51,Chicago,online,home delivery,0.28,promotional,pending,4
4,T0005,2024-03-30,C4760,P730,Canned Product 14,canned,2,13.97,Phoenix,cash,home delivery,4.17,regular,completed,4

In [8]:
## add a new column 'expensive' containing True or False value corresponds to unit_price
transactionDf['expensive'] = transactionDf['unit_price'] > 11 
transactionDf.head()

,transaction_id,transaction_date,customer_id,product_id,product_name,category,quantity,unit_price,store_location,payment_method,delivery_method,discount_used,demand_type,order_status,customer_rating,expensive
0,T0001,2024-08-13,C4310,P117,Beverage Product 6,beverage,5,17.94,New York,cash,home delivery,3.64,seasonal,cancelled,4,True
1,T0002,2024-11-22,C6417,P749,Canned Product 11,canned,10,7.04,Houston,credit card,pickup,1.67,promotional,completed,5,False
2,T0003,2024-10-28,C3303,P640,Beverage Product 3,beverage,1,14.19,Chicago,cash,digital download,2.32,seasonal,completed,2,True
3,T0004,2024-10-16,C7175,P126,Canned Product 3,canned,6,1.51,Chicago,online,home delivery,0.28,promotional,pending,4,False
4,T0005,2024-03-30,C4760,P730,Canned Product 14,canned,2,13.97,Phoenix,cash,home delivery,4.17,regular,completed,4,True

The following code aims at adding new columns `total_price` and `price_after_discount`. DataFrame allows for using calculation across columns. 

$price\_after\_discount = total\_price - (total\_price * discount\_used/100)$

The `round` function adjust the floating point of decimal values.

In [9]:
# Add a new column 'total_price' and 'price_after_discount'
transactionDf['total_price'] = transactionDf['quantity'] * transactionDf['unit_price']
transactionDf['price_after_discount'] = round(transactionDf['total_price'] - (transactionDf['total_price'] * transactionDf['discount_used']/100), 2)
transactionDf.head()

,transaction_id,transaction_date,customer_id,product_id,product_name,category,quantity,unit_price,store_location,payment_method,delivery_method,discount_used,demand_type,order_status,customer_rating,expensive,total_price,price_after_discount
0,T0001,2024-08-13,C4310,P117,Beverage Product 6,beverage,5,17.94,New York,cash,home delivery,3.64,seasonal,cancelled,4,True,89.70,86.43
1,T0002,2024-11-22,C6417,P749,Canned Product 11,canned,10,7.04,Houston,credit card,pickup,1.67,promotional,completed,5,False,70.40,69.22
2,T0003,2024-10-28,C3303,P640,Beverage Product 3,beverage,1,14.19,Chicago,cash,digital download,2.32,seasonal,completed,2,True,14.19,13.86
3,T0004,2024-10-16,C7175,P126,Canned Product 3,canned,6,1.51,Chicago,online,home delivery,0.28,promotional,pending,4,False,9.06,9.03
4,T0005,2024-03-30,C4760,P730,Canned Product 14,canned,2,13.97,Phoenix,cash,home delivery,4.17,regular,completed,4,True,27.94,26.77

In [10]:
# Drop the 'expensive' column
transactionDf.drop(columns=['expensive'], inplace=True)
transactionDf.head()

,transaction_id,transaction_date,customer_id,product_id,product_name,category,quantity,unit_price,store_location,payment_method,delivery_method,discount_used,demand_type,order_status,customer_rating,total_price,price_after_discount
0,T0001,2024-08-13,C4310,P117,Beverage Product 6,beverage,5,17.94,New York,cash,home delivery,3.64,seasonal,cancelled,4,89.70,86.43
1,T0002,2024-11-22,C6417,P749,Canned Product 11,canned,10,7.04,Houston,credit card,pickup,1.67,promotional,completed,5,70.40,69.22
2,T0003,2024-10-28,C3303,P640,Beverage Product 3,beverage,1,14.19,Chicago,cash,digital download,2.32,seasonal,completed,2,14.19,13.86
3,T0004,2024-10-16,C7175,P126,Canned Product 3,canned,6,1.51,Chicago,online,home delivery,0.28,promotional,pending,4,9.06,9.03
4,T0005,2024-03-30,C4760,P730,Canned Product 14,canned,2,13.97,Phoenix,cash,home delivery,4.17,regular,completed,4,27.94,26.77


## üìù Data Cleaning

In [11]:
# check for null values
transactionDf.isnull().sum()

transaction_id          0
transaction_date        0
customer_id             0
product_id              0
product_name            0
category                0
quantity                0
unit_price              0
store_location          0
payment_method          0
delivery_method         0
discount_used           0
demand_type             0
order_status            0
customer_rating         0
total_price             0
price_after_discount    0
dtype: int64

In [12]:
# check for NA values
transactionDf.isna().sum()

transaction_id          0
transaction_date        0
customer_id             0
product_id              0
product_name            0
category                0
quantity                0
unit_price              0
store_location          0
payment_method          0
delivery_method         0
discount_used           0
demand_type             0
order_status            0
customer_rating         0
total_price             0
price_after_discount    0
dtype: int64

In [13]:
# check for duplicate values
transactionDf.duplicated().sum()

np.int64(0)

In [14]:
# check for unique values
transactionDf.nunique()

transaction_id          50
transaction_date        46
customer_id             50
product_id              49
product_name            42
category                 5
quantity                10
unit_price              49
store_location           5
payment_method           3
delivery_method          3
discount_used           47
demand_type              3
order_status             3
customer_rating          5
total_price             50
price_after_discount    50
dtype: int64

You can run the following code to

* drop all rows containing null values

```python
df.dropna()
```

* drop all columns containing null values
```python
df.dropna(axis=1)
```

* replace null values with `100`
```python
df.fillna(100)
```

* replace null values of column `category` with `Beverage`
```python
df['category'].fillna('Beverage')
```

* replace null values of column `unit_price` with mean value
```python
df['unit_price'].fillna(df['unit_price'].mean())
```


## üîÉ Sorting Columns
### Sort one column

In [15]:
# Sort by quantity descending
transactionDf.sort_values(by='quantity', ascending=False)

,transaction_id,transaction_date,customer_id,product_id,product_name,category,quantity,unit_price,store_location,payment_method,delivery_method,discount_used,demand_type,order_status,customer_rating,total_price,price_after_discount
1,T0002,2024-11-22,C6417,P749,Canned Product 11,canned,10,7.04,Houston,credit card,pickup,1.67,promotional,completed,5,70.40,69.22
14,T0015,2024-02-14,C1651,P874,Snacks Product 4,snacks,10,19.62,New York,cash,pickup,3.06,promotional,pending,4,196.20,190.20
15,T0016,2024-11-01,C9950,P867,Canned Product 12,canned,10,5.52,Los Angeles,online,pickup,3.23,seasonal,completed,3,55.20,53.42
38,T0039,2024-07-14,C5400,P411,Frozen Product 13,frozen,10,12.19,Phoenix,online,pickup,1.31,regular,cancelled,3,121.90,120.30
13,T0014,2024-01-22,C6004,P732,Snacks Product 17,snacks,9,6.99,New York,online,home delivery,3.86,seasonal,cancelled,2,62.91,60.48
6,T0007,2024-05-27,C5791,P523,Dairy Product 3,dairy,9,13.20,New York,online,digital download,2.86,regular,cancelled,5,118.80,115.40
49,T0050,2024-11-07,C9997,P268,Frozen Product 18,frozen,9,14.19,Chicago,online,home delivery,4.78,regular,cancelled,3,127.71,121.61
25,T0026,2024-08-19,C2206,P673,Beverage Product 2,beverage,8,19.20,Phoenix,cash,home delivery,2.37,seasonal,cancelled,1,153.60,149.96
9,T0010,2024-09-17,C1560,P143,Frozen Product 14,frozen,8,15.36,Chicago,online,pickup,2.89,seasonal,cancelled,5,122.88,119.33
16,T0017,2024-09-18,C1143,P409,Canned Product 3,canned,8,16.48,Los Angeles,credit card,digital download,1.31,seasonal,cancelled,3,131.84,130.11
30,T0031,2024-09-05,C5413,P459,Dairy Product 16,dairy,8,18.65,Los Angeles,online,digital download,1.94,regular,completed,3,149.20,146.31
36,T0037,2024-05-27,C6386,P547,Dairy Product 18,dairy,8,8.09,New York,cash,home delivery,0.63,regular,cancelled,1,64.72,64.31
41,T0042,2024-08-02,C3536,P812,Dairy Product 18,dairy,8,11.64,Phoenix,online,digital download,3.22,promotional,pending,1,93.12,90.12
35,T0036,2024-12-01,C3422,P257,Snacks Product 12,snacks,8,8.89,Houston,credit card,pickup,0.72,regular,pending,5,71.12,70.61
23,T0024,2024-09-22,C7836,P124,Canned Product 12,canned,7,7.35,Chicago,cash,pickup,4.34,promotional,cancelled,2,51.45,49.22
5,T0006,2024-03-11,C2428,P179,Beverage Product 9,beverage,7,4.79,Los Angeles,cash,pickup,4.60,seasonal,pending,4,33.53,31.99
43,T0044,2024-10-03,C8021,P214,Canned Product 15,canned,7,11.87,New York,cash,pickup,0.49,seasonal,pending,1,83.09,82.68
47,T0048,2024-11-17,C1618,P391,Beverage Product 19,beverage,7,5.13,Chicago,credit card,pickup,3.97,seasonal,pending,5,35.91,34.48
33,T0034,2024-02-18,C8392,P583,Frozen Product 12,frozen,7,11.02,Chicago,credit card,digital download,0.33,promotional,pending,5,77.14,76.89
19,T0020,2024-03-23,C8152,P329,Dairy Product 11,dairy,7,4.60,Phoenix,cash,digital download,3.77,promotional,pending,2,32.20,30.99
40,T0041,2024-11-17,C1737,P879,Dairy Product 17,dairy,7,7.27,Los Angeles,credit card,digital download,4.09,promotional,cancelled,4,50.89,48.81
10,T0011,2024-01-25,C5446,P118,Canned Product 7,canned,6,5.55,Houston,credit card,pickup,2.99,seasonal,cancelled,4,33.30,32.30
3,T0004,2024-10-16,C7175,P126,Canned Product 3,canned,6,1.51,Chicago,online,home delivery,0.28,promotional,pending,4,9.06,9.03
42,T0043,2024-12-27,C9666,P986,Frozen Product 1,frozen,6,14.28,Phoenix,credit card,home delivery,2.03,promotional,completed,4,85.68,83.94
17,T0018,2024-02-26,C1983,P835,Snacks Product 5,snacks,6,17.36,Houston,cash,home delivery,4.01,seasonal,completed,1,104.16,99.98
0,T0001,2024-08-13,C4310,P117,Beverage Product 6,beverage,5,17.94,New York,cash,home delivery,3.64,seasonal,cancelled,4,89.70,86.43
34,T0035,2024-11-09,C4609,P614,Canned Product 9,canned,5,11.63,Chicago,online,home delivery,1.79,regular,cancelled,4,58.15,57.11
48,T0049,2024-12-17,C2410,P139,Dairy Product 19,dairy,5,18.83,Los Angeles,online,digital download,1.88,regular,completed,2,94.15,92.38
29,T0030,2024-04-01,C4962,P195,Beverage Product 1,beverage,5,3.43,Chicago,cash,digital download,0.62,seasonal,cancelled,3,17.15,17.04
27,T0028,2024-09-20,C4341,P103,Snacks Product 9,snacks,5,15.82,Los Angeles,cash,digital download,0.50,seasonal,completed,3,79.10,78.70
45,T0046,2024-07-16,C3608,P492,Canned Product 3,canned,4,15.69,Phoenix,online,digital download,2.44,promotional,pending,1,62.76,61.23
12,T0013,2024-10-28,C1505,P131,Frozen Product 8,frozen,4,18.36,Phoenix,credit card,home delivery,3.19,regular,cancelled,2,73.44,71.10
18,T0019,2024-05-12,C3221,P481,Beverage Product 10,beverage,4,2.73,New York,cash,home delivery,2.87,seasonal,pending,3,10.92,10.61
37,T0038,2024-09-11,C4242,P486,Beverage Product 11,beverage,4,11.84,New York,online,home delivery,0.81,seasonal,pending,4,47.36,46.98
28,T0029,2024-07-12,C5972,P759,Beverage Product 4,beverage,4,17.16,Houston,cash,pickup,3.27,regular,cancelled,3,68.64,66.40
31,T0032,2024-08-23,C5850,P404,Dairy Product 12,dairy,4,7.26,Chicago,credit card,home delivery,4.55,regular,pending,3,29.04,27.72
22,T0023,2024-02-13,C9908,P476,Dairy Product 11,dairy,3,6.06,Los Angeles,cash,digital download,3.97,regular,cancelled,3,18.18,17.46
21,T0022,2024-05-16,C3237,P867,Dairy Product 16,dairy,3,10.21,Los Angeles,cash,digital download,4.15,regular,pending,5,30.63,29.36
7,T0008,2024-09-02,C5584,P303,Snacks Product 7,snacks,3,2.59,Chicago,credit card,digital download,1.50,promotional,pending,1,7.77,7.65
46,T0047,2024-10-07,C8504,P101,Snacks Product 18,snacks,3,1.89,Houston,credit card,home delivery,3.50,seasonal,pending,2,5.67,5.47
24,T0025,2024-11-22,C3849,P229,Frozen Product 11,frozen,2,6.21,New York,online,digital download,3.91,seasonal,completed,4,12.42,11.93
4,T0005,2024-03-30,C4760,P730,Canned Product 14,canned,2,13.97,Phoenix,cash,home delivery,4.17,regular,completed,4,27.94,26.77
39,T0040,2024-06-22,C3967,P695,Dairy Product 7,dairy,2,13.67,Los Angeles,online,digital download,1.12,promotional,completed,5,27.34,27.03
32,T0033,2024-04-25,C9242,P724,Canned Product 17,canned,2,15.84,Los Angeles,online,digital download,1.08,regular,completed,5,31.68,31.34
26,T0027,2024-05-22,C6694,P247,Beverage Product 2,beverage,2,13.30,New York,credit card,digital download,4.07,promotional,cancelled,3,26.60,25.52
2,T0003,2024-10-28,C3303,P640,Beverage Product 3,beverage,1,14.19,Chicago,cash,digital download,2.32,seasonal,completed,2,14.19,13.86
11,T0012,2024-10-06,C9638,P517,Canned Product 16,canned,1,10.96,Phoenix,online,home delivery,3.94,seasonal,pending,5,10.96,10.53
8,T0009,2024-04-15,C3174,P395,Frozen Product 6,frozen,1,4.23,Los Angeles,cash,digital download,3.22,seasonal,completed,4,4.23,4.09
20,T0021,2024-03-26,C9515,P352,Snacks Product 9,snacks,1,11.88,Los Angeles,cash,pickup,3.18,regular,cancelled,5,11.88,11.50
44,T0045,2024-05-07,C5406,P373,Snacks Product 1,snacks,1,7.75,Houston,online,pickup,2.31,seasonal,pending,2,7.75,7.57

### Sort multiple columns

In [16]:
# Sort by quantity descending and unit_price ascending
transactionDf.sort_values(['quantity', 'unit_price'], ascending=[False, True])

,transaction_id,transaction_date,customer_id,product_id,product_name,category,quantity,unit_price,store_location,payment_method,delivery_method,discount_used,demand_type,order_status,customer_rating,total_price,price_after_discount
15,T0016,2024-11-01,C9950,P867,Canned Product 12,canned,10,5.52,Los Angeles,online,pickup,3.23,seasonal,completed,3,55.20,53.42
1,T0002,2024-11-22,C6417,P749,Canned Product 11,canned,10,7.04,Houston,credit card,pickup,1.67,promotional,completed,5,70.40,69.22
38,T0039,2024-07-14,C5400,P411,Frozen Product 13,frozen,10,12.19,Phoenix,online,pickup,1.31,regular,cancelled,3,121.90,120.30
14,T0015,2024-02-14,C1651,P874,Snacks Product 4,snacks,10,19.62,New York,cash,pickup,3.06,promotional,pending,4,196.20,190.20
13,T0014,2024-01-22,C6004,P732,Snacks Product 17,snacks,9,6.99,New York,online,home delivery,3.86,seasonal,cancelled,2,62.91,60.48
6,T0007,2024-05-27,C5791,P523,Dairy Product 3,dairy,9,13.20,New York,online,digital download,2.86,regular,cancelled,5,118.80,115.40
49,T0050,2024-11-07,C9997,P268,Frozen Product 18,frozen,9,14.19,Chicago,online,home delivery,4.78,regular,cancelled,3,127.71,121.61
36,T0037,2024-05-27,C6386,P547,Dairy Product 18,dairy,8,8.09,New York,cash,home delivery,0.63,regular,cancelled,1,64.72,64.31
35,T0036,2024-12-01,C3422,P257,Snacks Product 12,snacks,8,8.89,Houston,credit card,pickup,0.72,regular,pending,5,71.12,70.61
41,T0042,2024-08-02,C3536,P812,Dairy Product 18,dairy,8,11.64,Phoenix,online,digital download,3.22,promotional,pending,1,93.12,90.12
9,T0010,2024-09-17,C1560,P143,Frozen Product 14,frozen,8,15.36,Chicago,online,pickup,2.89,seasonal,cancelled,5,122.88,119.33
16,T0017,2024-09-18,C1143,P409,Canned Product 3,canned,8,16.48,Los Angeles,credit card,digital download,1.31,seasonal,cancelled,3,131.84,130.11
30,T0031,2024-09-05,C5413,P459,Dairy Product 16,dairy,8,18.65,Los Angeles,online,digital download,1.94,regular,completed,3,149.20,146.31
25,T0026,2024-08-19,C2206,P673,Beverage Product 2,beverage,8,19.20,Phoenix,cash,home delivery,2.37,seasonal,cancelled,1,153.60,149.96
19,T0020,2024-03-23,C8152,P329,Dairy Product 11,dairy,7,4.60,Phoenix,cash,digital download,3.77,promotional,pending,2,32.20,30.99
5,T0006,2024-03-11,C2428,P179,Beverage Product 9,beverage,7,4.79,Los Angeles,cash,pickup,4.60,seasonal,pending,4,33.53,31.99
47,T0048,2024-11-17,C1618,P391,Beverage Product 19,beverage,7,5.13,Chicago,credit card,pickup,3.97,seasonal,pending,5,35.91,34.48
40,T0041,2024-11-17,C1737,P879,Dairy Product 17,dairy,7,7.27,Los Angeles,credit card,digital download,4.09,promotional,cancelled,4,50.89,48.81
23,T0024,2024-09-22,C7836,P124,Canned Product 12,canned,7,7.35,Chicago,cash,pickup,4.34,promotional,cancelled,2,51.45,49.22
33,T0034,2024-02-18,C8392,P583,Frozen Product 12,frozen,7,11.02,Chicago,credit card,digital download,0.33,promotional,pending,5,77.14,76.89
43,T0044,2024-10-03,C8021,P214,Canned Product 15,canned,7,11.87,New York,cash,pickup,0.49,seasonal,pending,1,83.09,82.68
3,T0004,2024-10-16,C7175,P126,Canned Product 3,canned,6,1.51,Chicago,online,home delivery,0.28,promotional,pending,4,9.06,9.03
10,T0011,2024-01-25,C5446,P118,Canned Product 7,canned,6,5.55,Houston,credit card,pickup,2.99,seasonal,cancelled,4,33.30,32.30
42,T0043,2024-12-27,C9666,P986,Frozen Product 1,frozen,6,14.28,Phoenix,credit card,home delivery,2.03,promotional,completed,4,85.68,83.94
17,T0018,2024-02-26,C1983,P835,Snacks Product 5,snacks,6,17.36,Houston,cash,home delivery,4.01,seasonal,completed,1,104.16,99.98
29,T0030,2024-04-01,C4962,P195,Beverage Product 1,beverage,5,3.43,Chicago,cash,digital download,0.62,seasonal,cancelled,3,17.15,17.04
34,T0035,2024-11-09,C4609,P614,Canned Product 9,canned,5,11.63,Chicago,online,home delivery,1.79,regular,cancelled,4,58.15,57.11
27,T0028,2024-09-20,C4341,P103,Snacks Product 9,snacks,5,15.82,Los Angeles,cash,digital download,0.50,seasonal,completed,3,79.10,78.70
0,T0001,2024-08-13,C4310,P117,Beverage Product 6,beverage,5,17.94,New York,cash,home delivery,3.64,seasonal,cancelled,4,89.70,86.43
48,T0049,2024-12-17,C2410,P139,Dairy Product 19,dairy,5,18.83,Los Angeles,online,digital download,1.88,regular,completed,2,94.15,92.38
18,T0019,2024-05-12,C3221,P481,Beverage Product 10,beverage,4,2.73,New York,cash,home delivery,2.87,seasonal,pending,3,10.92,10.61
31,T0032,2024-08-23,C5850,P404,Dairy Product 12,dairy,4,7.26,Chicago,credit card,home delivery,4.55,regular,pending,3,29.04,27.72
37,T0038,2024-09-11,C4242,P486,Beverage Product 11,beverage,4,11.84,New York,online,home delivery,0.81,seasonal,pending,4,47.36,46.98
45,T0046,2024-07-16,C3608,P492,Canned Product 3,canned,4,15.69,Phoenix,online,digital download,2.44,promotional,pending,1,62.76,61.23
28,T0029,2024-07-12,C5972,P759,Beverage Product 4,beverage,4,17.16,Houston,cash,pickup,3.27,regular,cancelled,3,68.64,66.40
12,T0013,2024-10-28,C1505,P131,Frozen Product 8,frozen,4,18.36,Phoenix,credit card,home delivery,3.19,regular,cancelled,2,73.44,71.10
46,T0047,2024-10-07,C8504,P101,Snacks Product 18,snacks,3,1.89,Houston,credit card,home delivery,3.50,seasonal,pending,2,5.67,5.47
7,T0008,2024-09-02,C5584,P303,Snacks Product 7,snacks,3,2.59,Chicago,credit card,digital download,1.50,promotional,pending,1,7.77,7.65
22,T0023,2024-02-13,C9908,P476,Dairy Product 11,dairy,3,6.06,Los Angeles,cash,digital download,3.97,regular,cancelled,3,18.18,17.46
21,T0022,2024-05-16,C3237,P867,Dairy Product 16,dairy,3,10.21,Los Angeles,cash,digital download,4.15,regular,pending,5,30.63,29.36
24,T0025,2024-11-22,C3849,P229,Frozen Product 11,frozen,2,6.21,New York,online,digital download,3.91,seasonal,completed,4,12.42,11.93
26,T0027,2024-05-22,C6694,P247,Beverage Product 2,beverage,2,13.30,New York,credit card,digital download,4.07,promotional,cancelled,3,26.60,25.52
39,T0040,2024-06-22,C3967,P695,Dairy Product 7,dairy,2,13.67,Los Angeles,online,digital download,1.12,promotional,completed,5,27.34,27.03
4,T0005,2024-03-30,C4760,P730,Canned Product 14,canned,2,13.97,Phoenix,cash,home delivery,4.17,regular,completed,4,27.94,26.77
32,T0033,2024-04-25,C9242,P724,Canned Product 17,canned,2,15.84,Los Angeles,online,digital download,1.08,regular,completed,5,31.68,31.34
8,T0009,2024-04-15,C3174,P395,Frozen Product 6,frozen,1,4.23,Los Angeles,cash,digital download,3.22,seasonal,completed,4,4.23,4.09
44,T0045,2024-05-07,C5406,P373,Snacks Product 1,snacks,1,7.75,Houston,online,pickup,2.31,seasonal,pending,2,7.75,7.57
11,T0012,2024-10-06,C9638,P517,Canned Product 16,canned,1,10.96,Phoenix,online,home delivery,3.94,seasonal,pending,5,10.96,10.53
20,T0021,2024-03-26,C9515,P352,Snacks Product 9,snacks,1,11.88,Los Angeles,cash,pickup,3.18,regular,cancelled,5,11.88,11.50
2,T0003,2024-10-28,C3303,P640,Beverage Product 3,beverage,1,14.19,Chicago,cash,digital download,2.32,seasonal,completed,2,14.19,13.86

## üîç Filtering

In [17]:
# Filter transaction with quantity > 5 and unit_price <= 10
transactionDf[(transactionDf['quantity'] > 5) & (transactionDf['unit_price'] <= 10)]

,transaction_id,transaction_date,customer_id,product_id,product_name,category,quantity,unit_price,store_location,payment_method,delivery_method,discount_used,demand_type,order_status,customer_rating,total_price,price_after_discount
1,T0002,2024-11-22,C6417,P749,Canned Product 11,canned,10,7.04,Houston,credit card,pickup,1.67,promotional,completed,5,70.40,69.22
3,T0004,2024-10-16,C7175,P126,Canned Product 3,canned,6,1.51,Chicago,online,home delivery,0.28,promotional,pending,4,9.06,9.03
5,T0006,2024-03-11,C2428,P179,Beverage Product 9,beverage,7,4.79,Los Angeles,cash,pickup,4.60,seasonal,pending,4,33.53,31.99
10,T0011,2024-01-25,C5446,P118,Canned Product 7,canned,6,5.55,Houston,credit card,pickup,2.99,seasonal,cancelled,4,33.30,32.30
13,T0014,2024-01-22,C6004,P732,Snacks Product 17,snacks,9,6.99,New York,online,home delivery,3.86,seasonal,cancelled,2,62.91,60.48
15,T0016,2024-11-01,C9950,P867,Canned Product 12,canned,10,5.52,Los Angeles,online,pickup,3.23,seasonal,completed,3,55.20,53.42
19,T0020,2024-03-23,C8152,P329,Dairy Product 11,dairy,7,4.60,Phoenix,cash,digital download,3.77,promotional,pending,2,32.20,30.99
23,T0024,2024-09-22,C7836,P124,Canned Product 12,canned,7,7.35,Chicago,cash,pickup,4.34,promotional,cancelled,2,51.45,49.22
35,T0036,2024-12-01,C3422,P257,Snacks Product 12,snacks,8,8.89,Houston,credit card,pickup,0.72,regular,pending,5,71.12,70.61
36,T0037,2024-05-27,C6386,P547,Dairy Product 18,dairy,8,8.09,New York,cash,home delivery,0.63,regular,cancelled,1,64.72,64.31
40,T0041,2024-11-17,C1737,P879,Dairy Product 17,dairy,7,7.27,Los Angeles,credit card,digital download,4.09,promotional,cancelled,4,50.89,48.81
47,T0048,2024-11-17,C1618,P391,Beverage Product 19,beverage,7,5.13,Chicago,credit card,pickup,3.97,seasonal,pending,5,35.91,34.48


## üìä Grouping and Aggregation

In [18]:
transactionDf.groupby('category')['quantity'].agg(['mean', 'max', 'min'])

              mean  max  min
category
beverage  4.700000    8    1
canned    5.666667   10    1
dairy     5.818182    9    2
frozen    5.875000   10    1
snacks    5.111111   10    1

In [19]:
# multiple columns aggregation
transactionDf.groupby('category').agg({'total_price': ['mean', 'max', 'min'],'customer_rating': 'mean'})

         total_price                customer_rating
                mean     max    min            mean
category
beverage   49.760000  153.60  10.92        3.200000
canned     52.152500  131.84   9.06        3.416667
dairy      64.388182  149.20  18.18        3.090909
frozen     78.175000  127.71   4.23        3.750000
snacks     60.728889  196.20   5.67        2.777778

In [20]:
# multiple columns grouping and aggregation
transactionDf.groupby(['store_location','category']).agg({'total_price': ['count','mean', 'max', 'min'],
                                                          'discount_used': ['mean', 'std'],
                                                          'customer_rating': 'mean'})

                        total_price                             discount_used  \
                              count        mean     max     min          mean
store_location category
Chicago        beverage           3   22.416667   35.91   14.19      2.303333
               canned             3   39.553333   58.15    9.06      2.136667
               dairy              1   29.040000   29.04   29.04      4.550000
               frozen             3  109.243333  127.71   77.14      2.666667
               snacks             1    7.770000    7.77    7.77      1.500000
Houston        beverage           1   68.640000   68.64   68.64      3.270000
               canned             2   51.850000   70.40   33.30      2.330000
               snacks             4   47.175000  104.16    5.67      2.635000
Los Angeles    beverage           1   33.530000   33.53   33.53      4.600000
               canned             3   72.906667  131.84   31.68      1.873333
               dairy              6   61.731667  149.20   18.18      2.858333
               frozen             1    4.230000    4.23    4.23      3.220000
               snacks             2   45.490000   79.10   11.88      1.840000
New York       beverage           4   43.645000   89.70   10.92      2.847500
               canned             1   83.090000   83.09   83.09      0.490000
               dairy              2   91.760000  118.80   64.72      1.745000
               frozen             1   12.420000   12.42   12.42      3.910000
               snacks             2  129.555000  196.20   62.91      3.460000
Phoenix        beverage           1  153.600000  153.60  153.60      2.370000
               canned             3   33.886667   62.76   10.96      3.516667
               dairy              2   62.660000   93.12   32.20      3.495000
               frozen             3   93.673333  121.90   73.44      2.176667

                                  customer_rating
                              std            mean
store_location category
Chicago        beverage  1.675062        3.333333
               canned    2.052080        3.333333
               dairy          NaN        3.000000
               frozen    2.233391        4.333333
               snacks         NaN        1.000000
Houston        beverage       NaN        3.000000
               canned    0.933381        4.500000
               snacks    1.461928        2.500000
Los Angeles    beverage       NaN        4.000000
               canned    1.180522        3.666667
               dairy     1.359668        3.666667
               frozen         NaN        4.000000
               snacks    1.895046        4.000000
New York       beverage  1.446199        3.500000
               canned         NaN        1.000000
               dairy     1.576848        3.000000
               frozen         NaN        4.000000
               snacks    0.565685        3.000000
Phoenix        beverage       NaN        1.000000
               canned    0.939486        3.333333
               dairy     0.388909        1.500000
               frozen    0.948543        3.000000


## ‚úÖ References
- [User guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)
- [Cheat sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)